export const dateFormat = {
  MMMdoyyyy: "MMM do yyyy",
  DoMMM: "ddd, MMM DD",
  DMMM: "D MMM",
  YYYYMMDD: "YYYY-MM-DD",
  YYYYMMDDhhmmss: "YYYY-MM-DD hh:mm:ss",
  DDMMYYYY: "DD-MM-YYYY",
  DDMMMYYYY: "DD MMM YYYY",
  MMMD: "MMM D",
  MMMDDYYYY: "MMM DD YYYY",
  MMMDoYYYY: "MMMM Do, YYYY",
  hmmaz: "h:mm a z",
  hmm: "h:mm",
  hmma: "h:mm a",
  DDMMYY: "DD/MM/YY",
  iso: "YYYY-MM-DDTHH:mm:ss.SSSSZ",
  hmm_a: "h:mm a",
  MMMDD_YYYY: "MMM DD, YYYY",
  MMMMD_YYYY: "MMMM D, YYYY",
  YYYY_MM_DD: "YYYY/MM/DD",
  DoDhmma: "ddd D, h:mm a",
};
